config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :categories
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "sessions#new"
  
  resources :users 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      can :read, User, id: user.id
      if user.admin?
        can :read, :all
  
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
  validates :theme, presence: true, uniqueness: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :ideas
  validates :username, presence: true, uniqueness: true
  enum role: %w(default admin)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_url, alert: exception.message
end

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def redirect_unless_current_user_admin
    redirect_to login_path unless current_user.admin? 
  end

  def redirect_unless_current_user_exists
    redirect_to login_path unless current_user.present?
    
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:update, :show, :edit, :destroy]
  before_filter :redirect_unless_current_user_admin
  
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new(theme: params[:theme])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private 

  def set_category
    @cateogry = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:theme)
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :destroy, :update]
  before_filter :redirect_unless_current_user_exists
  before_filter :redirect_unless_current_user_admin, only: [:index]
  def index
    @ideas = Idea.all
  end

  def show
    # @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new(title: params[:title], body: params[:body], category_id: params[:category_id], user_id: current_user.id)
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @idea.update(idea_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to user_path(current_user)
  end

 private
  def set_idea
    @idea = Idea.find(params[:id])
  end

  def idea_params
    params.require(:idea).permit(:title, :body, :category_id, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

def create 
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successful Login"
      redirect_to user_path(@user)
    else
      flash[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Goodbye!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_unless_current_user_exists
  before_filter :authorize

  def index
  end
  def show
    @user = User.find(params[:id])  
    authorize! :read, @user 
    @ideas = @user.ideas
  end

    private
  def authorize
    if current_user.nil?
      redirect_to login_path, alert: "Not authorized"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :theme %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Category Home</h1>


<h4>List of Idea Categories:</h4>
<ul>
  <% @categories.each do |category| %>
    <li class = "category_item"><%= category.theme%> <%= link_to "Delete", category_path(category.id), method: :delete, :confirm => "Are you sure ?"  %> </li>
    <% end %>
</ul>

<%= link_to "Create A New Category", new_category_path  %>

app/views/categories/new.html.erb
<h1>Create a New Category</h1>

<%= render 'form' %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>

  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Idea %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :Details %><br>
    <%= f.text_field :body %>
  </div>
  <div>
  <%= f.collection_select(:category_id, Category.all, :id, :theme) %>
  </div>

   <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<h1>Idea Editor</h1>

<%= render 'form' %> 

app/views/ideas/index.html.erb
<h1>Idea Page</h1>
<ul>
<% @ideas.each do |idea|  %>
  <li> <strong><%=idea.category.theme  %></strong>: <%=link_to idea.title, idea %>: <%= idea.body %></li>
  <%end %>
</ul>

 



<%= link_to "New Idea", new_idea_path  %>

app/views/ideas/new.html.erb
<h1>New Idea Creation Station</h1>

<%= render 'form' %>


<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<h1>Idea Details</h1>

<h3>
  <strong>Idea:</strong>
  <%= @idea.title %>
</h3>

<p>
  <strong>Details:</strong>
  <%= @idea.body %>
</p>

<p>
  <strong>Category:</strong>
  <%= @idea.category.theme %>
</p>

<%= link_to 'Edit Idea', edit_idea_path(@idea) %>
<%= link_to("Bad Idea Remover", idea_path(@idea), method: :delete, :confirm => "Are you sure ?") %>
<%= link_to 'Back', user_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Idea Collector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<% if current_user.present? %>
  <% if current_user.admin? %>

    <%= button_to 'Create A Category', categories_path, method: :get, class: "button", class: "admin_button"  %>
    <%= button_to 'View All Ideas', ideas_path, method: :get, class: "button", class: "admin_button"%>
    <% User.all.each do |user| %>
    <%= button_to "View As User #{user.id} - #{user.username}", user_path(user), method: :get, class: "button", class: "admin_button" %>
    <% end %>
    
  <% end %>
  <%="You are logged in as #{current_user.username}"  %>
  <%= button_to 'log out', logout_path, method: :delete, class: "button" %>
  <%= button_to 'profile', user_path(current_user), method: :get, class: "button" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1> Welcome <%= @user.username %></h1>

<h3>Here are your ideas:</h3>
<ul>
<% @ideas.each do |idea| %>
  <li> <strong><%=idea.category.theme  %></strong>: <%=link_to idea.title, idea %>: <%= idea.body %></li>
  <% end %>
</ul>



<%= link_to "New Idea", new_idea_path  %>